### ISSUE TITLE
Navbar Suggestion

### ISSUE THREAD

**Issue by Zemerik** [Mac-Web/macvg#5]
To make your website look better and more attractive, I would suggest you change the navbar colour to transparent. 

Regards, 
Zemerik

**Comment by Mac-Web** [comment]
Dear Zemerik,
Thank you for your suggestion, we'll take that into account when we're updating our visuals and appearance.

MacWeb Team

**Comment by Mac-Web** [comment]
If you have any other suggestions or concerns, feel free to drop an issue or a pull request at any time! Thanks.

**Comment by Zemerik** [comment]
Thanks!!
